### ISSUE TITLE
Error creating build counter! Status Code: 404

### ISSUE THREAD

**Issue by codehunter13** [4tecture/BuildVersioning#14] opened 2019-03-19 12:39 UTC
Hi,
When using a self hosted agent, i get the error:
##[error]Error creating build counter! Status Code: 404
It works when using a agent hosted by microsoft.

Any idea?

"https://dev.azure.com/softwel/_apis/ExtensionManagement/InstalledExtensions/4tecture/BuildVersioning/Data/Scopes/Default/Current/Collections/BuildCounter/Documents?api-version=3.1-preview.1"   gives a 404 

full log:

##[debug]Evaluating condition for step: 'BuildVersioning'
##[debug]Evaluating: succeeded()
##[debug]Evaluating succeeded:
##[debug]=> True
##[debug]Result: True
##[section]Starting: BuildVersioning
==============================================================================
Task         : Build Versioning
Description  : Task to version build artifacts.
Version      : 0.8.12
Author       : 
Help         : [More Information](https://github.com/4tecture/BuildVersioning)
==============================================================================
##[debug]agent.TempDirectory=C:\vsts-agent-win-x86-2.146.0\_work\_temp
##[debug]loading inputs and endpoints
##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
##[debug]loading INPUT_BUILDNUMBERACTION
##[debug]loading INPUT_BUILDNUMBERVERSIONFORMAT
##[debug]loading INPUT_BUILDREGEXINDEX
##[debug]loading INPUT_CUSTOMBUILDREGEX
##[debug]loading INPUT_CUSTOMNUMBERVARIABLE
##[debug]loading INPUT_DOASSEMBLYINFOAPPENDSUFFIX
##[debug]loading INPUT_DOCONVERTASSEMBLYINFOTOLOWERCASE
##[debug]loading INPUT_DOINSTALLGITVERSION
##[debug]loading INPUT_DONUSPECUPDATEDEPENCENCY
##[debug]loading INPUT_DOREPLACEANDROID
##[debug]loading INPUT_DOREPLACEASSEMBLYINFO
##[debug]loading INPUT_DOREPLACECUSTOM
##[debug]loading INPUT_DOREPLACEDOTNETCORE
##[debug]loading INPUT_DOREPLACEIOS
##[debug]loading INPUT_DOREPLACENPM
##[debug]loading INPUT_DOREPLACENUSPEC
##[debug]loading INPUT_DOSHOWWARNINGSFORUNMATCHEDREGEX
##[debug]loading INPUT_EXCLUDEFILEPATTERN
##[debug]loading INPUT_FILEPATTERNANDROID
##[debug]loading INPUT_FILEPATTERNASSEMBLYINFO
##[debug]loading INPUT_FILEPATTERNCUSTOM
##[debug]loading INPUT_FILEPATTERNDOTNETCORE
##[debug]loading INPUT_FILEPATTERNIOS
##[debug]loading INPUT_FILEPATTERNNPM
##[debug]loading INPUT_FILEPATTERNNUSPEC
##[debug]loading INPUT_GITVERSIONINSTALLERURL
##[debug]loading INPUT_PARAMASSEMBLYFILEVERSION
##[debug]loading INPUT_PARAMASSEMBLYINFORMATIONALVERSION
##[debug]loading INPUT_PARAMASSEMBLYINFOSUFFIXTYPE
##[debug]loading INPUT_PARAMASSEMBLYVERSION
##[debug]loading INPUT_PARAMBUILDCOUNTERKEY
##[debug]loading INPUT_PARAMCUSTOMREPLACEREGEX
##[debug]loading INPUT_PARAMCUSTOMSEARCHREGEX
##[debug]loading INPUT_PARAMDOTNETCOREVERSIONTYPE
##[debug]loading INPUT_PARAMNPMVERSIONTYPE
##[debug]loading INPUT_PARAMNUSPECVERSIONTYPE
##[debug]loading INPUT_PARAMOVERWRITEFOURTHDIGITWITHBUILDCOUNTER
##[debug]loading INPUT_PARAMVERSIONCODE
##[debug]loading INPUT_SOURCEPATH
##[debug]loading INPUT_VERSIONFORMAT
##[debug]loading INPUT_VERSIONSOURCE
##[debug]loaded 44
##[debug]Agent.ProxyUrl=undefined
##[debug]Agent.CAInfo=undefined
##[debug]Agent.ClientCert=undefined
##[debug]Agent.SkipCertValidation=undefined
##[debug]Agent.ProxyUrl=undefined
##[debug]Agent.CAInfo=undefined
##[debug]Agent.ClientCert=undefined
##[debug]check path : C:\vsts-agent-win-x86-2.146.0\_work\_tasks\BuildVersioning_9e3e2353-692f-4804-9fc1-8a3bca551511\0.8.12\node_modules\azure-pipelines-tool-lib\lib.json
##[debug]adding resource file: C:\vsts-agent-win-x86-2.146.0\_work\_tasks\BuildVersioning_9e3e2353-692f-4804-9fc1-8a3bca551511\0.8.12\node_modules\azure-pipelines-tool-lib\lib.json
##[debug]system.culture=en-US
##[debug]Starting Build Versioning step
##[debug]versionSource=variable
##[debug]Build.BuildNumber=20190319.3
##[debug]buildRegexIndex=0
##[debug]buildNumberAction=nothing
##[debug]buildNumberVersionFormat=3
##[debug]customNumberVariable=softwelNgVersion
##[debug]softwelNgVersion=0.1.0.0
##[debug]VersionHandler: Using 0.1.0.0 for the custom version number
##[debug]Split version tokens: [0].[1].[0].[0]
##[debug]paramAssemblyVersion=4
##[debug]paramAssemblyFileVersion=4
##[debug]paramAssemblyInformationalVersion=4
##[debug]doAssemblyInfoAppendSuffix=false
##[debug]doConvertAssemblyInfoToLowerCase=false
##[debug]paramAssemblyInfoSuffixType=4
##[debug]set BuildVersion.MajorVersion=0
##[debug]Processed: ##vso[task.setvariable variable=BuildVersion.MajorVersion;issecret=false;]0
##[debug]Setting variable BuildVersion.MajorVersion to value 0
##[debug]set BuildVersion.MinorVersion=1
##[debug]Processed: ##vso[task.setvariable variable=BuildVersion.MinorVersion;issecret=false;]1
##[debug]Setting variable BuildVersion.MinorVersion to value 1
##[debug]set BuildVersion.PatchVersion=0
##[debug]Processed: ##vso[task.setvariable variable=BuildVersion.PatchVersion;issecret=false;]0
##[debug]Setting variable BuildVersion.PatchVersion to value 0
##[debug]paramOverwriteFourthDigitWithBuildCounter=true
##[debug]paramBuildCounterKey=Pleegzorg-$(BuildVersion.MajorVersion).$(BuildVersion.MinorVersion).$(BuildVersion.PatchVersion)
##[debug]BuildVersion.MajorVersion=0
##[debug]BuildVersion.MinorVersion=1
##[debug]BuildVersion.PatchVersion=0
##[debug]Getting credentials for local feeds
SYSTEMVSSCONNECTION exists true
##[debug]SYSTEMVSSCONNECTION exists true
##[debug]Got auth token
##[debug]Agent.ProxyUrl=undefined
##[debug]Get API URL: https://dev.azure.com/softwel/_apis/ExtensionManagement/InstalledExtensions/4tecture/BuildVersioning/Data/Scopes/Default/Current/Collections/BuildCounter/Documents/Pleegzorg-0.1.0?api-version=3.1-preview.1
##[debug]Getting credentials for local feeds
SYSTEMVSSCONNECTION exists true
##[debug]SYSTEMVSSCONNECTION exists true
##[debug]Got auth token
##[debug]Agent.ProxyUrl=undefined
##[debug]Post API URL: https://dev.azure.com/softwel/_apis/ExtensionManagement/InstalledExtensions/4tecture/BuildVersioning/Data/Scopes/Default/Current/Collections/BuildCounter/Documents?api-version=3.1-preview.1
##[debug]Post API Data: {"id":"Pleegzorg-0.1.0","count":1,"__etag":-1}
##[error]Error creating build counter! Status Code: 404
##[debug]Processed: ##vso[task.issue type=error;]Error creating build counter! Status Code: 404
##[debug]task result: Failed
##[error]Error creating build counter
##[debug]Processed: ##vso[task.issue type=error;]Error creating build counter
##[debug]Processed: ##vso[task.complete result=Failed;]Error creating build counter
##[debug]Leaving Build Versioning step
##[section]Finishing: BuildVersioning

**Comment by us292231** [comment] 2019-03-20 16:33
I get the same error on both a self-hosted build machine and a cloud (MS) hosted system.  

I have also tried using the latest api call with no success.

Jim

**Comment by us292231** [comment] 2019-03-28 13:18
Here is what I think needs to change in VersionCounterService.ts/.js:
- api-version=5.0-preview
- the 'targetUrl' needs to be extmgmt.${vstsinstance}

I was able to get the call to work in Postman with these changes on dev.azure.com

**Comment by marc-mueller** [comment] 2019-04-15 07:36
Thanks for reporting the issue. We are having a look at it. Looks like an URL mismatch  between on-premises and Azure DevOps Services.

**Comment by marc-mueller** [comment] 2019-08-21 07:32
This issue has been resolved with version 0.9.0 of the extension. The error was caused by the old url format (visualstudio.com) which is not working with newly created accounts.

**Closed as completed by marc-mueller** 2019-08-21 07:32 UTC
